export const T = {
  bg:            '#0d0d0d',
  panel:         '#111111',
  card:          '#1a1a1a',
  border:        '#252525',
  borderHover:   '#383838',
  text:          '#e2e0d9',
  muted:         '#686868',

  accent:        '#f59e0b',
  accentDim:     'rgba(245,158,11,0.12)',
  success:       '#34d399',

  preview:       '#f7f4ef',
  previewBorder: '#e0dbd0',
  previewBar:    '#ede9e1',

  font: "'IBM Plex Mono', 'Courier New', monospace",
}

export const DARK_PREVIEW = {
  bg:          '#141414',
  bar:         '#111111',
  border:      '#272727',
  paper:       '#1c1c1c',
  paperShadow: '0 4px 32px rgba(0,0,0,0.6)',
  paperBorder: '1px solid #2a2a2a',
  text:        '#d0cec8',
  muted:       '#888880',
  sectionLine: '#2e2e2e',
  btnColor:    '#9a9890',
  btnBorder:   '#2a2a2a',
  btnBg:       '#1c1c1c',
}

export const LIGHT_PREVIEW = {
  bg:          '#f7f4ef',
  bar:         '#ede9e1',
  border:      '#e0dbd0',
  paper:       '#fff',
  paperShadow: '0 4px 24px rgba(0,0,0,0.14)',
  paperBorder: 'none',
  text:        '#000',
  muted:       '#444',
  sectionLine: '#000',
  btnColor:    '#6a6560',
  btnBorder:   '#c8c2b5',
  btnBg:       '#e8e3da',
}

export const S = {
  input: {
    width: '100%',
    padding: '7px 10px',
    background: '#1a1a1a',
    border: '1px solid #252525',
    borderRadius: '5px',
    color: '#e2e0d9',
    fontSize: '12px',
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color .15s',
  },
  textarea: {
    width: '100%',
    padding: '7px 10px',
    background: '#1a1a1a',
    border: '1px solid #252525',
    borderRadius: '5px',
    color: '#e2e0d9',
    fontSize: '12px',
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    outline: 'none',
    boxSizing: 'border-box',
    resize: 'vertical',
    lineHeight: 1.55,
    transition: 'border-color .15s',
  },
  label: {
    display: 'block',
    fontSize: '10px',
    fontWeight: 600,
    color: '#686868',
    marginBottom: '5px',
    letterSpacing: '0.07em',
    textTransform: 'uppercase',
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
  },
  card: {
    background: '#1a1a1a',
    border: '1px solid #252525',
    borderRadius: '7px',
    padding: '13px',
    marginBottom: '9px',
  },
  btnPrimary: {
    padding: '7px 16px',
    background: '#f59e0b',
    color: '#0d0d0d',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 700,
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    letterSpacing: '0.05em',
  },
  btnGhost: {
    padding: '6px 12px',
    background: 'transparent',
    border: '1px solid #383838',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 500,
    color: '#c4c0b8',
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    letterSpacing: '0.03em',
  },
  divider: {
    height: '1px',
    background: '#252525',
    margin: '16px 0',
  },
}
